/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) intg_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s1[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s2[6] = {0, 3, 0, 0, 0, 0};

/* intg:(x0[2x3],p[1x3],z0[0x3],rx0[0x3],rp[0x3],rz0[0x3])->(xf[2x3],qf[0x3],zf[0x3],rxf[0x3],rqf[0x3],rzf[0x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  #error Code generation not supported for RungeKutta
  return 0;
}

CASADI_SYMBOL_EXPORT int intg(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int intg_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int intg_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void intg_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int intg_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void intg_release(int mem) {
}

CASADI_SYMBOL_EXPORT void intg_incref(void) {
}

CASADI_SYMBOL_EXPORT void intg_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int intg_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int intg_n_out(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_real intg_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* intg_name_in(casadi_int i){
  switch (i) {
    case 0: return "x0";
    case 1: return "p";
    case 2: return "z0";
    case 3: return "rx0";
    case 4: return "rp";
    case 5: return "rz0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* intg_name_out(casadi_int i){
  switch (i) {
    case 0: return "xf";
    case 1: return "qf";
    case 2: return "zf";
    case 3: return "rxf";
    case 4: return "rqf";
    case 5: return "rzf";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* intg_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* intg_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int intg_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 95;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
