/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpc_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#ifndef casadi_inf
  #define casadi_inf INFINITY
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s1[48] = {2, 15, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s2[27] = {1, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* solver:(x0[42],p[36],lbx[42],ubx[42],lbg[42],ubg[42],lam_x0[42],lam_g0[42])->(x[42],f,g[42],lam_x[42],lam_g[42],lam_p[36]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  #error Code generation not supported for IpoptInterface
  return 0;
}

/* helper:(i0[42],i1[36],i2[42])->(o0[1x12]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w0=w+0;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+30 : 0, 12, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  return 0;
}

/* MPC:(x0[2x3],xgoal[2x15])->(u_opt[1x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2, *cs;
  casadi_real *w0=w+6175, *w1=w+6217, *w2=w+6223, *w3=w+6229, *w4=w+6259, *w5=w+6295, *w6=w+6337, *w7=w+6379, *w8=w+6385, *w9=w+6391, *w10=w+6397, *w11=w+6409, *w12=w+6415, *w13=w+6457, *w14=w+6499, *w15=w+6541, *w16=w+6583, *w17=w+6625;
  /* #0: @0 = zeros(42x1) */
  casadi_clear(w0, 42);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 6, w1);
  /* #2: @2 = vec(@1) */
  casadi_copy(w1, 6, w2);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 30, w3);
  /* #4: @3 = vec(@3) */
  /* #5: @4 = vertcat(@2, @3) */
  rr=w4;
  for (i=0, cs=w2; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<30; ++i) *rr++ = *cs++;
  /* #6: @5 = -inf(42x1) */
  casadi_fill(w5, 42, -casadi_inf);
  /* #7: @6 = inf(42x1) */
  casadi_fill(w6, 42, casadi_inf);
  /* #8: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #9: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #10: @8 = zeros(6x1) */
  casadi_clear(w8, 6);
  /* #11: @9 = zeros(6x1) */
  casadi_clear(w9, 6);
  /* #12: @10 = all_-1(12x1) */
  casadi_fill(w10, 12, -1.);
  /* #13: @11 = vec(@1) */
  casadi_copy(w1, 6, w11);
  /* #14: @12 = vertcat(@2, @7, @8, @9, @10, @11) */
  rr=w12;
  for (i=0, cs=w2; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<6; ++i) *rr++ = *cs++;
  /* #15: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #16: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #17: @8 = zeros(6x1) */
  casadi_clear(w8, 6);
  /* #18: @9 = zeros(6x1) */
  casadi_clear(w9, 6);
  /* #19: @10 = ones(12x1) */
  casadi_fill(w10, 12, 1.);
  /* #20: @1 = vec(@1) */
  /* #21: @13 = vertcat(@2, @7, @8, @9, @10, @1) */
  rr=w13;
  for (i=0, cs=w2; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<6; ++i) *rr++ = *cs++;
  /* #22: @14 = zeros(42x1) */
  casadi_clear(w14, 42);
  /* #23: @15 = zeros(42x1) */
  casadi_clear(w15, 42);
  /* #24: {@16, NULL, NULL, NULL, @17, NULL} = solver(@0, @4, @5, @6, @12, @13, @14, @15) */
  arg1[0]=w0;
  arg1[1]=w4;
  arg1[2]=w5;
  arg1[3]=w6;
  arg1[4]=w12;
  arg1[5]=w13;
  arg1[6]=w14;
  arg1[7]=w15;
  res1[0]=w16;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=w17;
  res1[5]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @10 = helper(@16, @4, @17) */
  arg1[0]=w16;
  arg1[1]=w4;
  arg1[2]=w17;
  res1[0]=w10;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #26: output[0][0] = @10 */
  casadi_copy(w10, 12, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int MPC(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int MPC_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void MPC_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void MPC_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int MPC_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real MPC_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* MPC_name_in(casadi_int i){
  switch (i) {
    case 0: return "x0";
    case 1: return "xgoal";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* MPC_name_out(casadi_int i){
  switch (i) {
    case 0: return "u_opt";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int MPC_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 94;
  if (sz_res) *sz_res = 32;
  if (sz_iw) *sz_iw = 43;
  if (sz_w) *sz_w = 6667;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
